### PR TITLE
Camera-specific Settings (Rsolution, FPS, & Oth. Decoder Options) for DirectShow

### LINKED ISSUE #79: How to change width and height & fps form Camera?
Hi, everyone
  I am currently using `SIPSorceryMedia FFmpeg` pushed the stream from the camera (2K) to the streaming server and found that the stream delay was very high, not just on the Server side. I also used the `OnVideoSourceRawSampleFaster `callback to display on pictureBox, it also has high delay. I guest the resolution is too high and `FFMPEG `encoding takes too long. I want to lower the resolution of the image and increase FPS. What should I do? Thanks

My code below:

**Init**
          

           SIPSorceryMedia.FFmpeg.FFmpegInit.Initialise(FfmpegLogLevelEnum.AV_LOG_FATAL, LIB_PATH);
            var camera = FFmpegCameraManager.GetCameraDevices();
            videoSource = new FFmpegCameraSource(camera.FirstOrDefault().Path);
            videoSource.OnVideoSourceError += VideoSource_OnVideoSourceError;

            string MicrophoneDevicePath = "audio= (Realtek High Definition Audio)";
            audioSource = new SIPSorceryMedia.FFmpeg.FFmpegMicrophoneSource(MicrophoneDevicePath, new AudioEncoder());

            localPC.onicecandidate += LocalPC_onicecandidate1;`

**CreatePeerConnection**

            public void CreateLocalPeerConnection()
         {
            if (videoSource != null)
            {
                videoSource.RestrictFormats(x => x.Codec == VideoCodec);

                MediaStreamTrack videoTrack = new MediaStreamTrack(videoSource.GetVideoSourceFormats(), MediaStreamStatusEnum.SendOnly);
                localPC.addTrack(videoTrack);

                videoSource.OnVideoSourceRawSampleFaster += VideoSource_OnVideoSourceRawSampleFaster;
                videoSource.OnVideoSourceEncodedSample += localPC.SendVideo;
                localPC.OnVideoFormatsNegotiated += (videoFormats) => videoSource.SetVideoSourceFormat(videoFormats.First());
                localPC.OnVideoFormatsNegotiated += LocalPC_OnVideoFormatsNegotiated;

            }

            if (audioSource != null)
            {
                audioSource.RestrictFormats(x => x.Codec == AudioCodec);

                MediaStreamTrack audioTrack = new MediaStreamTrack(audioSource.GetAudioSourceFormats(), MediaStreamStatusEnum.SendOnly);
                localPC.addTrack(audioTrack);

                audioSource.OnAudioSourceError += AudioSource_OnAudioSourceError;
                
                audioSource.OnAudioSourceEncodedSample += AudioSource_OnAudioSourceEncodedSample;
                localPC.OnAudioFormatsNegotiated += LocalPC_OnAudioFormatsNegotiated;
            }

            //Exchange SDP with streaming media
            RTCSessionDescriptionInit localSDP = localPC.createOffer(null);
            PushVideo(localSDP.sdp);
        }

             public bool PushVideo(string sdp)
        {
            try
            {
                var content = new StringContent(sdp, Encoding.UTF8, "application/json");
                SdpModel result = Task.Run(async () => await PostAsync(pushUrl, content)).Result;

                localPC.SetRemoteDescription(SdpType.answer, SDP.ParseSDPDescription(result.sdp));
                return true;
            }
            catch (Exception ex)
            {
                return false;
            }
        }

**CallBack**

        private void VideoSource_OnVideoSourceRawSampleFaster(uint durationMilliseconds, RawImage rawImage)
        {
            localPictureBox.Invoke(new Action(() =>
            {
                Bitmap bmpImage = new Bitmap(rawImage.Width, rawImage.Height, rawImage.Stride, PixelFormat.Format24bppRgb, rawImage.Sample);
                localPictureBox.Image = bmpImage;
            }));
        }

        private void LocalPC_OnAudioFormatsNegotiated(List<AudioFormat> obj)
        {
            audioSource.SetAudioSourceFormat(obj.First());
            audioSource.StartAudio();
        }

        private void LocalPC_OnVideoFormatsNegotiated(List<VideoFormat> obj)
        {
            videoSource.SetVideoSourceFormat(obj.First());
            videoSource.StartVideo();
        }

        private void AudioSource_OnAudioSourceEncodedSample(uint durationRtpUnits, byte[] sample)
        {
            localPC.SendAudio(durationRtpUnits, sample);
        }

### PR DESCRIPTION
**Pull request by ha-ves**
May resolve #79.

### Summary:

- [x] **DirectShow** camera/input devices formats/options parsing from FFmpeg,
- [x] Camera settings (video resolution, framerates, & other decoder-related options), It is added as an additional functions instead of in the constructor for simplicity,
    - **(Simple)** Restricts filter for formats to be used (pixel_format, resolution, & fps),
    - **(Advanced)** Restricts filter for device options to be used (specific to the input format),
    - **(Pre-configured Advanced)** Sets the device options manually which usually is a preconfigured set of options (specific to the input format),
- [ ] Not yet tested for other input formats (avfoundation, v4l2, etc.), but they should be compatible by default.

A bit considerations:
- [ ] Caches the found cameras? Because the backward compatibility will need to re-parse the FFmpeg output. But unless the backward compatibility users spawn multiple camera sources in a loop as fast as possible, I don't think it's worth it,
- [ ] Though there is no confirmation on the actual resolution and framerate being used also no exception handle yet.

### Additions:
- New `Camera` properties
```c#
public class Camera
{
    // general purpose pixel_format structure
    public struct CameraFormat
    {
        public AVPixelFormat PixelFormat;
        public int Width;
        public int Height;
        public double FPS;
    }
    // formats from FFmpeg
    public List<CameraFormat>? AvailableFormats {  get; set; }

    // Other specific non-pixel_format (e.g. vcodec/etc.)
    public List<Dictionary<string, string>>? AvailableOptions { get; set; }
/// ... ///
}

```
- New methods & constructor to `FFmpegCameraSource` with `Camera`:
```c#
public unsafe class FFmpegCameraSource : FFmpegVideoSource
{
    // Cameras now have formats, so get the camera object instead of only the path
    public FFmpegCameraSource(Camera camera) { /// ... /// }

    // Backward compatibility for providing only path is to re-enumerate the cameras to get the corresponding camera
    // and fallback to just the path
    public FFmpegCameraSource(string path) : this(FFmpegCameraManager.GetCameraByPath(path) ?? new() { Path = path }) { /// ... /// }

// Simple, filter from the generally available rawvideo formats
public void RestrictCameraFormats(Predicate<Camera.CameraFormat> formatFilter) { /// ... /// }

// Advanced, filter from all available format options
public void RestrictCameraOptions(Predicate<Dictionary<string, string>> optFilter) { /// ... /// }
/// ... ///
}
/// ... ///
public unsafe class FFmpegCameraManager
{
    // re-parse FFmpeg camera devices to "reverse lookup" for a path
    static public Camera? GetCameraByPath(string path) => GetCameraDevices()?.FirstOrDefault(x => x.Path == path);
    /// ... ///
}
```
- New methods usage example
```c#
var localvid = new FFmpegCameraSource(FFmpegCameraManager.GetCameraDevices()!.First());
/// ... ///
// Simple, set the camera resolution to anything up to 480 with fps more than 15
localvid.RestrictCameraFormats(cam => cam.Width <= 480 && cam.Height <= 480 && cam.FPS >= 15);

// Advanced, set the decoder to use any vcodec=mjpeg option
localvid.RestrictCameraOptions(opts =>
{
    return opts.Keys.Contains("vcodec") && opts["vcodec"] == "mjpeg";
});

// Most advanced set the options manually, you probably know FFmpeg/libAV* enough to use this.
localvid.SetCameraDeviceOptions(new() { /// ... /// });
```

### CODE REVIEW

**Comment by ha-ves** [comment]
I have another potential PR if this one is approved.

It's for eliminating unnecessary swscale for converting pixel format where there are already matching pixel format between decoded frame and encoder

**Comment by ChristopheI** [comment]
Thank you for this PR.
Why you don't just use GetDShowLibCameras() ?

What happens when using GetDShowLogsForDevice() if ffmpeg is currently outputting other info in same time ?
And also perhaps someone is already using a specific ffmpeg callback.

**Comment by ha-ves** [comment]
> Thank you for this PR. Why you don't just use GetDShowLibCameras() ?

I'm not sure when a camera/device name that uses Unicode will be able to come through the FFmpeg wrapper.

> What happens when using GetDShowLogsForDevice() if ffmpeg is currently outputting other info in same time ? And also perhaps someone is already using a specific ffmpeg callback.

It would only filter for camera options.

Since FFmpeg has a single entry/output for logging, it's better to put it in a single LogHelper class so any specific log callback uses would not deregister the other and missing log output.

**Comment by ChristopheI** [comment]
Thank you for this PR.

**Pull request merged**
